link:
  layout:
    footer:
      author: "https://github.com/hainnsunasterisk"
      news: "https://news.railstutorial.org/"
  static_pages:
    home:
      link_ruby_on_rails: https://www.railstutorial.org/
    help:
      link_ruby_on_rails_help: https://www.railstutorial.org/help
      link_ruby_on_rails_book: https://www.railstutorial.org/book
    about:
      link_ruby_on_rails_tutorial: https://www.railstutorial.org
      link_learn_enough: https://www.learnenough.com
      link_about_description_book: https://www.railstutorial.org/book
      link_about_description_series: https://screencasts.railstutorial.org
      link_about_description_ror: https://rubyonrails.org
    contact:
      link_contact_page: https://www.railstutorial.org/contact
variables:
  static_pages:
    home:
      image_width: 200px
validations:
  user:
    email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i'
    name_minlength: 5
    name_maxlength: 50
    email_minlength: 15
    email_maxlength: 255
    password_minlength: 6
    password_maxlength: 15
form:
  checkbox: "1"
pagination:
  per_page: 10
gravatar:
  link: "https://gravatar.com/emails"
time:
  expired: 2
